# Generated by Django 5.1 on 2024-09-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
