# Generated by Django 5.1 on 2024-09-20 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile-pics/default.jpg', upload_to='profile-pics')),
                ('bio', models.TextField()),
                ('followers', models.ManyToManyField(blank=True, related_name='user_following', to='User.profile')),
                ('following', models.ManyToManyField(blank=True, related_name='user_followers', to='User.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
